<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="myProjectCss.css">
    <title>About Bananas</title>
</head>
<header class="wrapper clearfix">
    <h1><a href="home.phtml">BANANA REPO</a> </h1>

    <div id="banner">
        <div id="logo"><a href="home.phtml"><img src="banana.jpg" width=250 height=150 lt="logo"></a></div>
    </div>


    <div id="cssmenu">
        <ul>
            <li class="current"><a href="home.phtml">Home</a></li>
            <li><a href="shop.phtml">Shop</a></li>
            <li><a href="contact.phtml">Contact</a></li>
            <li><a href="about.phtml">About Bananas</a></li>
        </ul>
    </div>

</header><!-- end header -->

<br>

<br>

<br>
<body>

<h1>Cool facts about bananas.</h1>



<br>

<br>

<br>
<div id="list">
    <ol>
        <li>The strings that go up and down the length of bananas are called Phloem Bundles. They help distribute nutrients to every part of the growing bananas.
        <li>The yellow bananas that are most often sold in supermarkets are sometimes called “dessert bananas” because they are soft and sweet.
        <li>Plantains are a type of banana that are not as sweet and are usually cooked. While not as commonly eaten in North America, plantains are a dietary staple in many tropical regions.
        <li>It is believed by many experts that bananas were the first fruit cultivated by humans.
        <li>Alexander the Great first came across bananas in India in 327 B.C.
        <li>Bananas were introduced to the United States at the 1876 Philadelphia Centennial Celebration, where they were sold wrapped in foil for 10 cents each.
        <li>Worldwide, bananas are the fourth largest fruit crop.
        <li>The average American consumes 28 pounds of bananas per year.
        <li>The banana peel is edible, though perhaps not very palatable unless cooked.
        <li>About 50 percent of people who are allergic to latex are often also allergic to bananas.
        <li>India is the #1 banana producer in the world.
        <li>The most popular banana cultivar in the world is the Cavendish. This is the banana most often seen in U.S. and European markets.
        <li>Before Cavendish, Gros Michel was the main banana cultivar exported on a mass, commercial scale. In the mid-20th century, Gros Michel was ravaged by Panama disease and is no longer sold commercially.
        <li>Panama disease, or Fusarium wilt, is a fungus that attacks banana plants. It was reported in Australia in the 19th century.
        <li>It is believed that the Cavendish, like the Gros Michel, will be devastated by Panama disease within 20 years and will no longer be able to be produced commercially. This would be a difficult blow to the banana industry.
        <li>Scientists are trying to develop a hybrid, disease-resistant banana.
        <li>Chiquita was initially called the United Fruit Company. In the 20th century, they played a controversial role in the politics of Central America, where they had vast holdings. The company earned the nickname of “The Octopus” in the region because they had their hands in so many political pots.
        <li>The CIA-sponsored 1954 coup that overthrew the democratically-elected Guatemalan government headed by Jacobo Arbenz Guzmán is believed to be a direct result of influence by the United Fruit Company, which had an antagonistic relationship with the Arbenz government.
        <li>In Uganda, bananas are such a big part of the diet that the same word, matooke, is used for both “food” and “banana.”
        <li>The pejorative term “banana republic” was coined by American writer O. Henry. He used it in reference to Honduras, but the term became widely used in reference to any Latin American, Caribbean, or African country that was politically unstable, relied heavily on basic agriculture, and was not technologically advanced.
        <li>The banana split was invented in 1904 by 23-year-old David Evans Strickler, an employee at the Tassel Pharmacy soda fountain in Latrobe, Pennsylvania.
        <li>The song “Yes, We Have No Bananas” was released in 1923 and became a huge hit. It refers to the banana shortage at the time.
        <li>In 2001, Britain recorded 300 incidents of injuries related to bananas. The majority of these involved people slipping on banana peels.





    </ol>

    <br>

    <br>
    <br>




</div>





</body>
<footer>

<div id="colophon" class="wrapper clearfix">
    Author:Joshua Budimir
    <a href="home.phtml">@BananaRepoLLC</a>
</div>

    </footer>
</html>