<!DOCTYPE html>
<!--[if lt IE 7]>    <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">

    <title>Project 1</title>
    <meta name="description" content="about bananas / selling">
    <meta name="keywords" content="just banana things">
    <link rel="stylesheet" type="text/css" href="myProjectCss.css">
    <!-- Mobile viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

</head>





<header class="wrapper clearfix">
    <a href="index.php">BANANA REPO</a>

    <div id="banner">
        <div id="logo"><a href="index.php"><img src="banana.jpg" width=250 height=150 lt="logo"></a></div>
    </div>


    <div id="cssmenu">
        <ul>
            <li class="current"><a href="home.phtml">Home</a></li>
            <li><a href="shop.phtml">Shop</a></li>
            <li><a href="contact.phtml">Contact</a></li>
            <li><a href="about.phtml">About Bananas</a></li>
        </ul>
    </div>



</header><!-- end header -->

<body id="home">

<br>
<br>
<h2> What is a banana?</h2>
<br>
<h1>A <u><i><b>magical</b></i></u> yellow fruit </h1>




<br>




<br>

<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/O5wRCbhbbuQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
<br>

<br>

<br>

<br>

<br>

<h2><b>So what?</b></h2>

<a href="shop.phtml"><h1>BUY OUR WIDE VARIETY OF FRESH BANANAS!!!</h1></a>
<br>

<br>
<!-- main content area
<form style="align-content: center" action="contact.php">

    <p>Email: <input type="text" name="email"></p>
    <p><input type="submit" name="submit"></p>


</form>
-->









<div id="form1" align="center">
<form action="search.php" method="get">
    <table>
        <tr>
            <th colspan="2">Research bananas</th>
        </tr>
        <tr>
            <td> Site to search for bananas on: </td>
            <td>
                <select name="site">
                    <option value="google">Google Web
                    <option value="googlei">Google Images
                    <option value="duck">DuckDuckGo
                    <option value="wiki">Wikipedia
                </select>
            </td>
        </tr>
        <tr>
            <td>Search some more about bananas while here:</td>
            <td>
                <input type="text" name="terms" size="25" maxlength="25">
            </td>
        <tr>
            <td colspan="2">
                <input type="submit" size="large" value= "Submit" class="centercell">
            </td>
        </tr>
    </table>
</form>

</div>




</body>



    <?php //include 'footer.phtml'; ?>



<br>




    <footer>
    <div id="colophon" class="wrapper clearfix">
        Author:Joshua Budimir
        <a href="home.phtml">@BananaRepoLLC</a>
    </div>

</footer>

</html>


