<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" type="text/css" href="myProjectCss.css">
<head>
    <meta charset="UTF-8">

    <title>Shop</title>
</head>
<header class="wrapper clearfix">
    <h1><a href="home.phtml">BANANA REPO</a> </h1>

    <div id="banner">
        <div id="logo"><a href="home.phtml"><img src="banana.jpg" width=250 height=150 lt="logo"></a></div>
    </div>


    <div id="cssmenu">
        <ul>
            <li class="current"><a href="home.phtml">Home</a></li>
            <li><a href="shop.phtml">Shop</a></li>
            <li><a href="contact.phtml">Contact</a></li>
            <li><a href="about.phtml
">About Bananas</a></li>
        </ul>
    </div>

</header><!-- end header -->


<br>

<br>

<br>

<body>
<h1> Shop </h1>

<br>

<br>

<br>


<div id="shopform" align="left" >

    <table width="100%">
        <tr>
            <td> Item # <p> (click for description)</p> </td>
            <td> Name </td>
            <td> Price </td>

        </tr>
        <tr>
            <td><a href="shop.php"> 1 </a></td>
            <td> Cavendish bananas </td>
            <td> 3.99/lb </td>

        </tr>
        <tr>
            <td><a href="shop.php"> 2 </a></td>
            <td> Apple bananas</td>
            <td> 2.99/lb </td>

        </tr>
        <tr>
            <td><a href="shop.php"> 3 </a></td>
            <td> Lady Finger bananas</td>
            <td> 1.99/lb </td>

        </tr>
        <tr>
            <td> <a href="shop.php"> 4 </a></td>
            <td> Red bananas</td>
            <td> 5.99/lb </td>

        </tr>
        <tr>
            <td><a href="shop.php"> 5 </a></td>
            <td> Cooking bananas</td>
            <td> 8.99/lb </td>

        </tr>
        <tr>
            <td> <a href="shop.php"> 6 </a></td>
            <td> Pisanj Raja bananas</td>
            <td> 10.99/lb</td>

        </tr>





    </table>

    <br>

    <br>

</div>



<a href="https://www.teepublic.com/t-shirts?query=bananas"><h1 align="center"> CLICK FOR BANANA MERCHANDISE </h1></a>

</body>
<br>

    <br>

<footer>
    <div id="colophon" class="wrapper clearfix">
        Author:Joshua Budimir
        <a href="home.phtml">@BananaRepoLLC</a>
    </div>

</footer>
</html>